name: Check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Check update and update README
        run: |
          .\scripts\check-update.ps1

      - name: Commit and push changes
        run: |
          git config --local user.email "abgohxf@outlook.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "[bot] update README"
          git push
