name: Check

on:
  workflow_dispatch:
  schedule:
    # At minute 20 past every 4th hour.
    - cron: "20 */4 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check update and update README
        run: |
          .\scripts\check-update.ps1

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automatically update README"
          git push
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: abgox/gh-workflow-keepalive@main
