name: Update Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: windows-latest
    steps:
      - name: Configure Git
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update
        shell: pwsh
        run: |
          git clone --depth 1 https://${{ secrets.PAT_TOKEN }}@github.com/abgox/schema-docs.git schema-docs
          cd schema-docs
          .\scripts\download-schema-json.ps1
          git add .
          git commit -m "chore: automatically update some content"
          git push --force
