name: Update

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Handle schema, check update and update README
        run: |
          .\scripts\handle-schema.ps1
          .\scripts\check-update.ps1

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automatically update README and generate compressed files"
          git push
